### ISSUE TITLE
"Mac OS only."

### ISSUE THREAD

**Issue by kethinov** [Fraser-Greenlee/highlight-element#1]
It says in the extensions list that this works on Mac OS only, but I've confirmed that it does indeed also work in Windows.

**Comment by Fraser-Greenlee** [comment]
My bad, left it from another extansion I made, fixed it now.

**Comment by fluxxus** [comment]
@Fraser-Greenlee I know this is not a place to ask such things, but could you tell me which theme and font are you using in the readme screenshot?

**Comment by Fraser-Greenlee** [comment]
Hi I think I was using the standard style with my show-tabs extension but Im not sure.
